spring:
  application:
    name: api
  profiles: real
  datasource:
    url: jdbc:mariadb://3.35.140.126:3306/messenger
    driver-class-name: org.mariadb.jdbc.Driver
    username: messengerUser
    password: dbmessenger1234!@
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MariaDB102Dialect
    show-sql: true
logging:
  config: classpath:logback-prod.xml

cloud:
  aws:
    credentials:
      accessKey: AKIAU2UABLWF2JG2HL65
      secretKey: 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
    s3:
      bucket: serobucket
    region:
      static: ap-northeast-2
    stack:
      auto: false